server:
  port: ${SERVER_PORT:8080}
spring:
  application:
    name: claude-code-hooks
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}
  threads:
    virtual:
      enabled: true
  jackson:
    property-naming-strategy: SNAKE_CASE
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      probes:
        enabled: true
      show-details: ${MANAGEMENT_HEALTH_SHOW_DETAILS:when_authorized}
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
logging:
  level:
    root: ${LOG_LEVEL_ROOT}