service:
  security:
    cors:
      max-age: ${CORS_MAX_AGE_SECONDS:3600}
      allow-credentials: ${CORS_ALLOW_CREDENTIALS:true}
      allowed-headers: ${CORS_ALLOWED_HEADERS:Content-Type,Authorization,X-Requested-With}
      allowed-methods: ${CORS_ALLOWED_METHODS}
      allowed-origins: ${CORS_ALLOWED_ORIGINS}